[simanda]
user = www-data
group = www-data
listen = /var/run/php/php8.3-fpm.sock

pm = ondemand
pm.max_children = 8
pm.process_idle_timeout = 10s
pm.max_requests = 300

php_admin_value[upload_max_filesize] = 10M
php_admin_value[post_max_size] = 12M
php_admin_value[memory_limit] = 256M
php_admin_value[max_execution_time] = 120

; OPcache Optimization
php_admin_value[opcache.enable] = 1
php_admin_value[opcache.memory_consumption] = 128
php_admin_value[opcache.max_accelerated_files] = 20000
php_admin_value[opcache.validate_timestamps] = 0
